### ISSUE TITLE
程序被 Windows Defender 认定为病毒「Trojan:Win32/Fuery.B!cl」

### ISSUE THREAD

**Issue by illuz** [davidsmithgf/NoSQLBooster4MongoCleaner#1]
Trojan:Win32/Fuery.B!cl：https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fFuery.B!cl&threatid=2147718514

**Comment by davidsmithgf** [comment]
1.程序仅包含命令行删除文件与注册表删除特定键值，可能行为会被判定病毒；
2.编译，使用的是[Quick Batch File Compiler](https://www.abyssmedia.com/quickbfc/)，不知是否与此编译相关，你可以随便写个cmd命令打包试试，看是否也报病毒；
3.个人只使用kaspersky与bitdefender(病毒特征库都是更新最新的，不同机器上装的)，均未报病毒，一直可正常使用；
4.如怀疑有病毒，请勿下载使用；
